name: build packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_package:
    name: Build package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux-intel, linux-arm, windows-10, windows-11, macOS-intel, macOS-arm]
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
            archs: x86_64
          - os: linux-arm
            runs-on: ubuntu-24.04-arm64
            archs: aarch64
          - os: windows
            runs-on: windows-latest
            archs: x86_64
          - os: macos-intel
            # macos-13 was the last x86_64 runner
            runs-on: macos-13
            archs: x86_64
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
            archs: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.0

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_package, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      # TODO: enable this when ready
      #- uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #   repository-url: https://test.pypi.org/legacy/
