name: test package

on:
  push:
    branches:
      - main
      - 28-setup-workflow   # temporary for debugging
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - "docs/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        robot-version: ["4.1", "5.0", "6.0", "6.1", "7.0", "7.1", "7.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }} environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pipx install hatch

      - name: Install Robot Framework ${{ matrix.robot-version }}
        run: pip install robotframework==${{ matrix.robot-version }}

      - name: Create Hatch environment
        run: hatch env create

      - name: Run Python Tests
        run: hatch run python-tests

      - name: Run Robot Framework Tests
        run: hatch run robot-tests

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-os-${{ matrix.os }}-py-${{ matrix.python-version }}-robotframework-${{ matrix.robot-version }}
          path: test-results

  publish-test-results:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          path: test-results

      - name: Install Robot Framework
        run: pip install robotframework

      - name: Merge Test Results
        run: rebot --outputdir merged-results --merge test-results/**/*.xml

      - name: Upload Merged Test Results
        uses: actions/upload-artifact@v4
        with:
          name: merged-test-results
          path: merged-results
