name: test package

on:
  push:
    branches:
      - main
      - 28-setup-workflow # temporary for debugging
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - "docs/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        robot-version: ["4.1", "5.0", "6.0", "6.1", "7.0", "7.1", "7.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }} environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Hatch environment
        id: cache-hatch
        uses: actions/cache@v3
        with:
          path: ~/.local/share/hatch/env
          key: ${{ runner.os }}-hatch-${{ matrix.python-version }}-${{ matrix.robot-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-hatch-

      - name: Install Hatch
        if: steps.cache-hatch.outputs.cache-hit != 'true'
        run: pipx install hatch

      - name: Create Hatch environment
        if: steps.cache-hatch.outputs.cache-hit != 'true'
        run: hatch env create

      - name: Install Robot Framework ${{ matrix.robot-version }}
        run: hatch run pip install robotframework==${{ matrix.robot-version }}

      - name: Run Python Tests
        run: hatch run python-tests

      - name: Run Robot Framework Tests
        run: hatch run robot-tests --outputdir test-results/os-${{ matrix.os }}-py-${{ matrix.python-version }}-rf-${{ matrix.robot-version }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-os-${{ matrix.os }}-py-${{ matrix.python-version }}-robotframework-${{ matrix.robot-version }}
          path: test-results

  publish-test-results:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Cache Downloaded Test Results
        id: cache-test-results
        uses: actions/cache@v3
        with:
          path: test-results
          key: ${{ runner.os }}-test-results-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-results-

      - name: Download Test Results
        if: steps.cache-test-results.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4

      - name: Cache Python environment for Robot Framework
        id: cache-python-rf
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-rf-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-rf-

      - name: Install Robot Framework
        if: steps.cache-python-rf.outputs.cache-hit != 'true'
        run: pip install robotframework

      - name: Merge Test Results
        run: rebot --name Robotframework_Tests --outputdir merged-results test-os-*/os-*/output.xml

      - name: Upload Merged Test Results
        uses: actions/upload-artifact@v4
        with:
          name: merged-test-results
          path: merged-results
