name: test package

on:
  push:
    branches:
      - main
      - 28-setup-workflow   # temporary for debugging
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - "docs/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        robot-version: ["4.1", "5.0", "6.0", "6.1", "7.0", "7.1", "7.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }} environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pipx install hatch

      - name: Install Robot Framework ${{ matrix.robot-version }}
        run: pip install robotframework==${{ matrix.robot-version }}

      - name: Create Hatch environment
        run: hatch env create

      - name: Run Python Tests
        run: hatch run python-tests

      - name: Run Robot Framework Tests
        run: hatch run robot-tests
